package com.genymobile.scrcpy;

/**
 * Build constants.
 *
 * In upstream scrcpy, this class is generated by the Gradle build (buildFeatures.buildConfig). It is provided as a regular source file here so
 * that the module can be compiled in the Android source tree (Soong), where no BuildConfig is generated for a java_library.
 */
public final class BuildConfig {

    public static final boolean DEBUG = false;

    // Must match the upstream baseline version (scrcpy v4.1)
    public static final String VERSION_NAME = "4.1";

    private BuildConfig() {
        // not instantiable
    }
}
